### PR TITLE
Explicit connection timeout and KeyboardInterrupt handling

### PR DESCRIPTION
**Pull request by ogrisel**
Abort download attempts after 5s (and retry as if it was a server-side error). This makes it possible to download the full datasets in one go much more reliably on my machine:

```
$ python generate_questions.py --corpus=dailymail --mode=download
Downloading URLs for the training set:
100.00% [196961/196961]
Downloading URLs for the validation set:
100.00% [12148/12148]
Downloading URLs for the test set:
100.00% [10397/10397]
```

Also make it possible to interrupt (and later resume) the download mode with "ctrl-C" by handling the `KeyboardInterrupt` exception.

I can split the two contributions into 2 pull requests if you prefer.

### CODE REVIEW

**Comment by ogrisel** [comment]
I just submitted the CLA.

**Comment by lespeholt** [comment]
Thanks! :-) I'm amazed that this is enough to get it to work in one go. For me, Wayback Machine has been very unstable with some pages not being available for a long time.

**Comment by ogrisel** [comment]
I could already run it twice on from 2 different machines (both for CNN and dailymail) and it worked in one go each time.

**Comment by ogrisel** [comment]
Without this fix, some connections are stalled without limit. I suspect that wayback machine has an anti-DDOS mechanism that drops packets without closing the TCP connection under load.

**Comment by lespeholt** [comment]
Hi,

I just pushed a fix introduced in this branch where missing_urls.txt wasn't written correctly. I encourage you to run it again.

**Comment by ogrisel** [comment]
Oops, I thought I had tested it with ctrl-c... Sorry for the oversight.

**Pull request merged**
