### PR TITLE
Petrux requirements

### PR DESCRIPTION
**Pull request by petrux**
Just a minor improvement: virtualenv configuration via `requirements.txt` file. Feel free to reject. :-)  
P.S. I signed the CLA but I think it's stil pending...

### CODE REVIEW

**Comment by lespeholt** [comment]
Thanks :-) I apologize for the long delay, I haven't received Github notifications.

**Comment by lespeholt** [comment]
Thanks :-) I apologize for the long delay, I haven't received Github notifications.

**Comment by petrux** [comment]
> I haven't received Github notifications.  

Happened the same here. :-)  

Best,
Giulio  

##

**Comment by lespeholt** [comment]
Reverted because a wget command for 'requirements.txt' is needed to make everything work. I will gladly  accept if it's added :-)

**Comment by petrux** [comment]
Agreed. Just give me a couple of hours (or maybe a couple of couples of hours). ;-)

**Comment by petrux** [comment]
Done. Please, take a look and let me know!

**Comment by petrux** [comment]
@lespeholt any news?

**Comment by lespeholt** [comment]
Hi,

I've been on vacation but your changes are going in now :-)

**Comment by petrux** [comment]
Oh, I see! Very good, I hope you had a great time on vacation. Thanks! ;-)

**Pull request merged**
